use_default_settings: true

general:
  instance_name: "Paper Finder Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "changeme"  # Change this in production!
  limiter: false
  image_proxy: true
  method: "POST"
  
ui:
  static_use_hash: true
  default_locale: "en"
  theme_args:
    simple_style: "auto"
  
engines:
  # Semantic Scholar
  - name: semantic scholar
    engine: xpath
    search_url: https://www.semanticscholar.org/search?q={query}
    results_xpath: //div[contains(@class, "cl-paper-row")]
    url_xpath: .//a[@data-selenium-selector="paper-link"]/@href
    title_xpath: .//h3[@data-selenium-selector="paper-title"]/span
    content_xpath: .//div[@data-selenium-selector="paper-abstract"]
    categories: [science]
    disabled: false
    
  # arXiv  
  - name: arxiv
    engine: arxiv
    shortcut: arx
    categories: science
    disabled: false
    
  # Google Scholar
  - name: google scholar
    engine: google_scholar
    shortcut: gos
    categories: science
    disabled: false
    
  # PubMed
  - name: pubmed
    engine: pubmed
    shortcut: pub
    categories: science
    disabled: false
    
  # Core.ac.uk
  - name: core
    engine: core
    categories: science
    disabled: false

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

# Disable unwanted engines
disabled_engines:
  - bing
  - google videos
  - google news
  - google images
  - duckduckgo
  - startpage
